### ISSUE TITLE
Adding Icons

### ISSUE THREAD

**Issue by ZucchiniZe** [jbranchaud/splitting-atoms#64] opened 2014-03-14 01:37 UTC
I think we need to add a real favicon plus a real logo.
## Here are some resources

[favicon](https://atom.io/favicon.ico)
[logo base](http://og.github.com/atom-mark/atom-mark@1200x630.png)

**Comment by DWiechert** [comment] 2014-03-14 02:14
Do you know the licenses on those icons? We don't want to be using them if they're copyrighted.

**Comment by jbranchaud** [comment] 2014-03-14 02:25
I agree we need a real icon, but I would like to use something that is under creative commons (or similarly permissive) and preferably custom for Splitting Atoms. I am hesitant to use Atom's icon because that isn't our brand, plus this guide isn't affiliated with it.

**Comment by jbranchaud** [comment] 2014-03-14 02:40
Closing, duplicate of #51.

**Closed as completed by jbranchaud** 2014-03-14 02:40 UTC
